---

- name: Install Apache Web Server
  hosts: webservers
  become: yes

  tasks:
    - name: install apache
      yum: name=httpd state=latest

    - name: Start Apache
      service: name=httpd state=started enabled=yes
